drop table if exists roles cascade;
drop table if exists book cascade;
drop table if exists comment cascade;
drop table if exists users cascade;
create table roles (
                        admin_id bigint generated by default as identity,
                        user_id bigint,
                        role varchar(255),
                        primary key (admin_id)
);
create table book (
                      availability boolean not null,
                      price float(24) not null,
                      book_id bigint generated by default as identity,
                      author varchar(255),
                      book_name varchar(255),
                      description varchar(255),
                      cover_photo blob,
                      primary key (book_id)
);
create table comment (
                         comment_id bigint generated by default as identity,
                         ticket_id bigint,
                         user_id bigint,
                         context varchar(255),
                         primary key (comment_id)
);
create table users (
                       user_id bigint generated by default as identity,
                       delivery_address varchar(255),
                       email varchar(255),
                       first_name varchar(255),
                       last_name varchar(255),
                       password varchar(255),
                       username varchar(255),
                       primary key (user_id)
);
alter table if exists roles
    add constraint FKgc8dtql9mkq268detxiox7fpm
        foreign key (user_id)
            references users;
alter table if exists comment
    add constraint FKh57y35t42ni0uum64h4rnwau8
        foreign key (ticket_id)
            references book;
alter table if exists comment
    add constraint FKqm52p1v3o13hy268he0wcngr5
        foreign key (user_id)
            references users;