create table if not exists admin (
    admin_id bigint generated by default as identity,
    user_id bigint,
    primary key (admin_id),
    foreign key (user_id) references users
);

create table if not exists book (
    availability boolean not null,
    price float(24) not null,
    book_id bigint generated by default as identity,
    author varchar(255),
    book_name varchar(255),
    description varchar(255),
    cover_photo blob,
    primary key (book_id)
);

create table if not exists cart_item (
    quantity integer not null,
    book_id bigint,
    cart_id bigint,
    cart_item_id bigint generated by default as identity,
    primary key (cart_item_id),
    foreign key (book_id) references book,
    foreign key (cart_id) references shopping_cart
);

create table if not exists comment (
    comment_id bigint generated by default as identity,
    ticket_id bigint,
    user_id bigint,
    context varchar(255),
    primary key (comment_id),
    foreign key (ticket_id) references book,
    foreign key (user_id) references users
);

create table if not exists shopping_cart (
    cart_id bigint generated by default as identity,
    user_id bigint,
    primary key (cart_id),
    foreign key (user_id) references users
);

create table if not exists users (
    user_id bigint generated by default as identity,
    delivery_address varchar(255),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    username varchar(255),
    primary key (user_id)
);